version: '3.8'

services:
  budget-manager:
    # Nom du conteneur
    container_name: budget-manager
    
    # Build depuis le Dockerfile local
    build:
      context: .
      dockerfile: Dockerfile
    
    # Ports (externe:interne)
    # Changez 8080 par le port que vous voulez sur votre NAS
    ports:
      - "8080:80"
    
    # Redémarrage automatique
    restart: unless-stopped
    
    # Variables d'environnement (optionnel)
    environment:
      - TZ=Europe/Paris
    
    # Volumes pour persister les données (optionnel)
    # Décommentez si vous voulez sauvegarder les données hors du conteneur
    # volumes:
    #   - ./data:/usr/share/nginx/html/data
    
    # Réseau (optionnel)
    networks:
      - budget-network
    
    # Labels pour Traefik (si vous utilisez Traefik)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.budget.rule=Host(`budget.votre-domaine.com`)"
      - "traefik.http.services.budget.loadbalancer.server.port=80"
      # SSL avec Let's Encrypt (si configuré)
      # - "traefik.http.routers.budget.tls=true"
      # - "traefik.http.routers.budget.tls.certresolver=letsencrypt"
    
    # Healthcheck
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  budget-network:
    driver: bridge
